# Naive Bayes: Predicting survival from titanic crash

- P(A/B) = P(B/A) * P(A) / P(B) -> Conditional Probability <br>

- Bayes theroem -> P (Survived / Male & Class & Age & Cabin & Fare)<br>

- I am supposing/ or making a 'Naive' assumptio that featrues such as male, class, age, cabin, fare etc. are independent of each other <br>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("titanic.csv")
df

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",2,male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,"Graham, Miss. Margaret Edith",1,female,19.0,0,0,112053,30.0000,B42,S,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0
889,890,"Behr, Mr. Karl Howell",1,male,26.0,0,0,111369,30.0000,C148,C,1
890,891,"Dooley, Mr. Patrick",3,male,32.0,0,0,370376,7.7500,NaN,Q,0

In [3]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

i drop these columns becoz for me now they are not relevant to learn anive byas

In [4]:
inputs = df.drop('Survived',axis='columns')
target = df.Survived

In [5]:
#inputs.Sex = inputs.Sex.map({'male': 1, 'female': 2})

In [6]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head(3)

   female   male
0   False   True
1    True  False
2    True  False

In [7]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

   Pclass     Sex   Age     Fare  female   male
0       3    male  22.0   7.2500   False   True
1       1  female  38.0  71.2833    True  False
2       3  female  26.0   7.9250    True  False

I am dropping male column as well because of dummy variable trap theory. One column is enough to repressent male vs female

In [8]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs.head(3)

   Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True

In [9]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [10]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [11]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head()

   Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True
3       1  35.0  53.1000    True
4       3  35.0   8.0500   False

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.3)

In [14]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [21]:
model.fit(X_train,y_train)

# we use naive gussian method when data is in normal distribution

GaussianNB()

In [22]:
model.score(X_test,y_test)

0.8022388059701493

In [23]:
X_test[0:10]

     Pclass        Age      Fare  female
608       2  22.000000   41.5792    True
871       1  47.000000   52.5542    True
85        3  33.000000   15.8500    True
293       3  24.000000    8.8500    True
425       3  29.699118    7.2500   False
760       3  29.699118   14.5000   False
438       1  64.000000  263.0000   False
564       3  29.699118    8.0500    True
674       2  29.699118    0.0000   False
52        1  49.000000   76.7292    True

In [24]:
y_test[0:10]

608    1
871    1
85     1
293    0
425    0
760    0
438    0
564    0
674    0
52     1
Name: Survived, dtype: int64

In [25]:
model.predict(X_test[0:10])

array([1, 1, 1, 1, 0, 0, 1, 1, 0, 1])

In [26]:
model.predict_proba(X_test[:10])

array([[1.93998632e-01, 8.06001368e-01],
       [5.15793928e-02, 9.48420607e-01],
       [4.49645578e-01, 5.50354422e-01],
       [4.16036737e-01, 5.83963263e-01],
       [9.64050064e-01, 3.59499364e-02],
       [9.64973880e-01, 3.50261198e-02],
       [1.79675713e-11, 1.00000000e+00],
       [4.35932066e-01, 5.64067934e-01],
       [9.20019953e-01, 7.99800473e-02],
       [1.93357449e-02, 9.80664255e-01]])

Calculate the score using cross validation

In [27]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.792     , 0.752     , 0.744     , 0.80645161, 0.75      ])